In [2]:
import numpy as np
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.random.randint(0, 10)

2

In [23]:
np.random.randint(0, 100,(3,3))

array([[53, 18, 99],
       [22, 68, 33],
       [11, 23, 97]])

In [34]:
 np.random.randint(1, 100, (10, 10))

array([[14, 92, 33, 64, 81, 18,  3, 64, 89, 42],
       [24, 56, 50, 25, 91, 63, 33, 31, 92, 92],
       [62, 41, 27,  3, 87, 22,  9, 28, 80, 69],
       [93,  4, 46, 35, 72, 29,  9, 33, 52, 91],
       [67, 84, 18, 39, 26, 78, 52,  3, 62, 29],
       [86, 44, 64,  6, 77, 85, 40, 57, 94, 33],
       [80, 24, 58, 77, 52, 11, 98, 16, 40, 92],
       [81, 50, 61, 87, 48, 42, 33, 39, 89,  2],
       [77, 13, 49, 24, 59, 33, 33, 91, 41, 14],
       [80, 35, 49, 12, 20, 34,  4, 94, 58, 44]])

In [42]:
np.random.seed(101)
arr1 = np.random.randint(0, 100, 10)
arr1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [45]:
arr1.max()

95

In [46]:
arr1.min()

9

In [47]:
arr1.argmax()

0

In [48]:
arr1.argmin()

7

In [49]:
arr1.mean()

60.8

In [54]:
arr1.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [62]:
mat = np.arange(0, 100).reshape(10, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
mat[5, 3]

53

In [67]:
mat[7, :] #row

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [69]:
mat[:, 3] #col

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [71]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])